/**
 * Shape of `environment.ts` / `environment.prod.ts`, which are generated by
 * `set-env.mjs` from `.env` and are gitignored (do not commit IMS values).
 */
export const environment = {
  production: false,
  imsClientId: '',
  imsOrg: null as string | null,
};
