/**
 * Shape of `environment.ts` / `environment.prod.ts`, which are generated by
 * `set-env.mjs` from `.env` and are gitignored (do not commit IMS values).
 */
export const environment = {
  production: false,
  // In order to obtain an imsClientId you will need to raise a support ticket with Adobe.
  // Client Id's created via Adobe Developer Console will not work for Content Advisor.
  imsClientId: '',
  imsOrg: null as string | null,
};
